[package]
name = "das_woerterbuch"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
calamine = "0.19.1"
rand = "0.8.5"
colored = "2.0.0"
